=== KoBiykgl/java8/Java8Training/resources/Demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Demo"
	xmlns:tns="http://www.example.org/Demo" elementFormDefault="qualified">

    <element name="Person" type="tns:PersonType"></element>

	<complexType name="PersonType">
		<sequence>
			<element name="Name" type="string"></element>
			<element name="Address" type="tns:AddressType"></element>
		</sequence>
	</complexType>

    <complexType name="AddressType">
    	<sequence>
    		<element name="Number" type="unsignedInt"></element>
    		<element name="Street" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== KoBiykgl/java8/Java8Training/resources/Demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Person xmlns:tns="http://www.example.org/Demo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Demo Demo.xsd ">
	<tns:Name>Koray</tns:Name>
	<tns:Address>
		<tns:Number>19230</tns:Number>
		<tns:Street>Kadikoy</tns:Street>
	</tns:Address>
	<tns:Address>
		<tns:Number>19231</tns:Number>
		<tns:Street>Levent</tns:Street>
	</tns:Address>
	<tns:Address>
		<tns:Number>19232</tns:Number>
		<tns:Street>Etiler</tns:Street>
	</tns:Address>
</tns:Person>
